name: Java CI with Maven (use runner JDK)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check system Java
        run: java -version

      - name: Set JAVA_HOME from system java
        shell: bash
        run: |
          JDIR="$(readlink -f "$(which java)" | sed 's:/bin/java$::')"
          echo "JAVA_HOME=$JDIR" >> $GITHUB_ENV
          echo "JAVA_HOME set to $JDIR"
          java -XshowSettings:properties -version 2>&1 | sed -n '1,40p'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven (system mvn)
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
